# conda env create --file environment.yml
name: prueba
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - fs
  - jupyter
  - jupyterlab
  - pathlib
  - pip
  - pyprojroot
  - python=3.7
  - pip:
    - pyhere
    